name: Node.js CI

on:
  push:
    branches:
      - main

  workflow_dispatch:

  schedule:
    # Runs at 00:00 UTC daily.
    - cron: '0 0 * * *'

jobs:
  build:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - run: node index.js

    - name: setup git config
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git config pull.rebase false

    - name: commit
      run: |
        git add -A
        git commit -m "chore: automatic image update" || true
        git push
